application:
  name: '@pom.artifactId@'
  description: '@pom.description@'
  version: '@pom.version@'

server:
  port: 8080

jwt:
  secretKey: ${JWT_SECRET_KEY}

management:
  endpoint:
    shutdown.enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

spring:

  security:
    user:
      name: dnaanalyzer
      password: ${SECURITY_PASSWORD}

  datasource:
    url: jdbc:${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      minimumIdle: 10
      maximumPoolSize: 10

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true

  jackson:
    default-property-inclusion: non_null
    deserialization:
      adjust-dates-to-context-time-zone: false
