version: '3'

services:
  postgres:
    image: postgres:11.4
    environment:
      POSTGRES_USER: dnaanalyzer
      POSTGRES_PASSWORD: dnaanalyzer
    expose:
      - 5432
    ports:
      - 5433:5432
